### ISSUE TITLE
Autodesk Fusion 360 becomes almost useless for hobbyists ... 🙄 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#32]
https://hackaday.com/2020/09/16/autodesk-announces-major-changes-to-fusion-360-personal-use-license-terms/
Thread: https://news.ycombinator.com/item?id=24503950

Need to login to my account and see how this affects my future with the software.
I've been considering switching to Blender ... But obviously that's a whole new learning curve / workflow. ⏳

**Comment by iteles** [comment]
Yea, this very much sucks, they're basically excluding a whole bunch of small makers for no reason other than greed:

> Perhaps most importantly to the makerverse, STEP, SAT, and IGES file types can no longer be exported, the most common files for those who want to edit a design using different software

🙄

**Comment by iteles** [comment]
Note a current offer (unspecified time period) for Fusion 360 yearly subscription making it _slightly_ more accessible. 

Still much more keen on trialling freecad #35 for now.

![image](https://user-images.githubusercontent.com/4185328/94988557-1e6a0600-0566-11eb-842b-06930d7d59a0.png)

**Comment by nelsonic** [comment]
@iteles I don't _mind_ spending money on tools that help me get my job done like Zoom or GitHub.
What I mind is tools that _hike_ prices and cut out features for _beginners_; it's a myopic business decision.

**Comment by nelsonic** [comment]
Closing. Goto FreeCAD #35
