### ISSUE TITLE
Chore: Transfer `LightBurn` License from Thomson Laptop [dead] to Lenovo X230

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-cad-cam-cnc#63]
We've been happily using **`LightBurn`** https://github.com/dwyl/learn-cad-cam-cnc/issues/44 for the past few months. ⚡ 
Sadly, the **`Thomson Laptop`** we were using as our interface to the laser died. 💀 😢 
So I revived our _ancient_ **`Lenovo X230`** ("Windows Test Machine") and it runs **`LightBurn`** (`32bit`) fine. 👌 
Our **`LightBurn`** license only allows 2 devices... ✌️ 
So we need to _transfer_ the license from one PC to the other ... 🙄 

Hopefully this won't be too tedious. 🤞

**Comment by LuchoTurtle** [comment]
@nelsonic It worked perfectly (with one hiccup 😉 ). 
Turned out amazing, cannot thank you enough 🙏

**Comment by nelsonic** [comment]
@LuchoTurtle thanks for confirming. 👌 

The laser-cut box for your DIY Battery https://github.com/LuchoTurtle/diy-battery is looking great! 😍 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/194400/184839152-d1ca091a-d831-4854-b684-d791abfaae43.png">




Our two activations are now the "TEST" (Lenovo `X230`) and `THINKCENTER` (Dedicated `CAD` Desktop machine):
https://lightburn.cryptlex.app/me/licenses/d5551ff2-6848-49ac-8d22-4d88caaf645d/activations
![image](https://user-images.githubusercontent.com/194400/184838197-e2e38207-6ec6-41a8-a623-e38e0bf1f146.png)

**Comment by nelsonic** [comment]
Closing as this is working. ✅ 
Next: #64
